#!/bin/bash

# Read the input from the user
input_lines=$1

keys=()
values=()
while read -r line; do
    IFS=': ' read -r key value <<< "$line"
    values+=("$value")
    keys+=("$key")
done < $1

# Convert array to tab-separated string for the TSV header
header=$(IFS=$'\t'; echo "${keys[*]}")
# Append header to the TSV file if it doesn't exist
tsv_file="clay/comics.tsv"

if [[ ! -f "$tsv_file" ]]; then
    echo -e "$header" >> "$tsv_file"
fi

row=$(IFS=$'\t'; echo "${values[*]}")
echo -e "$row" >> "$tsv_file"

echo "Data appended to $tsv_file successfully!"
